"""a simple test program for the pcModule to communicate with the glorious Gloria storage robot"""
from pcModule import pcModule
gloria=pcModule("localhost")
gloria.updateSensors()
gloria.start()
def testAllSensors():
    print("error codes:")
    print(gloria.getErrorCodes())
    print("linesensor:")
    print(gloria.getLineSensor())
    print("left distance")
    print(gloria.getDistanceSensor()[0])
    print("right distance")
    print(gloria.getDistanceSensor()[1])
    print("armposition X:")
    print(gloria.getArmPosition()[0])
    print("armposition Y:")
    print(gloria.getArmPosition()[1])
    print("armposition Z:")
    print(gloria.getArmPosition()[2])
    print("armposition Pitch:")
    print(gloria.getArmPosition()[3])
    print("armposition wrist:")
    print(gloria.getArmPosition()[4])
    print("armposition grip:")
    print(gloria.getArmPosition()[5])
    print("latest calibration was done:")
    print(gloria.getCalibration())
    print("motors in auto mode:")
    print(gloria.getAutoMotor())
    print("arm in auto mode: ")
    print(gloria.getArmAuto())  
print(gloria.getSensorList())
gloria.setMotorSpeed(75, 75)
gloria.updateSensors()
print(gloria.getSensorList())
gloria.setArmPosition(10, 20, 30, 40, 50, 60)
gloria.updateSensors()
print(gloria.getSensorList())
testAllSensors()
gloria.calibrate()
gloria.setAutoMotor(False)
gloria.setAutoArm(True)
gloria.updateSensors()
print(gloria.getSensorList())

