/*
 * huvud_styr_protocol.h
 *
 * Created: 2014-11-14 16:00:55
 *  Author: Hannes
 */ 


#ifndef HUVUD_STYR_PROTOCOL_H_
#define HUVUD_STYR_PROTOCOL_H_

#define COMMAND_INSTRUCTION_MASK 0xF0
#define COMMAND_ADDRESS_MASK 0x0F
#define COMMAND_ACTION 0x30
#define COMMAND_SET_REG 0x10
#define COMMAND_SET_JOINT_SPEED 0x20
#define COMMAND_STATUS 0x40

#define ADDRESS_ALL 0x0F
#define ADDRESS_ARM 0x0E
#define ADDRESS_JOINT_1 0x02
#define ADDRESS_JOINT_2 0x03
#define ADDRESS_JOINT_3 0x04
#define ADDRESS_JOINT_4 0x05
#define ADDRESS_JOINT_5 0x06
#define ADDRESS_JOINT_6 0x07
#define ADDRESS_MOTOR_ALL 0x0D
#define ADDRESS_MOTOR_R 0x00
#define ADDRESS_MOTOR_L 0x01


#endif /* HUVUD_STYR_PROTOCOL_H_ */